package fractal

FRACTAL_PAN_FACTOR :: 0.05
FRACTAL_ZOOM_FACTOR :: 0.075
FRACTAL_MOUSE_DRAG_SCALE :: 1.0
FRACTAL_MIN_ZOOM :: 0.1
FRACTAL_MAX_ZOOM :: 1.0e9

FRACTAL_MIN_ITERATIONS :: 10
FRACTAL_MAX_ITERATIONS :: 2000
FRACTAL_ITERATION_STEP :: 10

FRACTAL_DEFAULT_ZOOM :: 0.5
FRACTAL_DEFAULT_CENTER_X :: -0.5
FRACTAL_DEFAULT_CENTER_Y :: 0.0
FRACTAL_DEFAULT_MAX_ITER :: 250
