name: build

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  linux:
    name: Linux (x86_64)
    uses: ./.github/workflows/build-linux.yml
    with:
      odin_version: dev-2026-08
      sdl_version: 3.4.2
  windows:
    name: Windows (x86_64)
    uses: ./.github/workflows/build-windows.yml
    with:
      odin_version: dev-2026-08
      sdl_version: 3.4.2
  macos-arm64:
    name: macOS (arm64)
    uses: ./.github/workflows/build-macos-arm64.yml
    with:
      odin_version: dev-2026-08
      sdl_version: 3.4.2
  macos-x86_64:
    name: macOS (x86_64)
    uses: ./.github/workflows/build-macos-x86_64.yml
    with:
      odin_version: dev-2026-08
      sdl_version: 3.4.2
